### PR TITLE
Update/babel optional chaining

### PR DESCRIPTION
**Pull request by enuchi**
See #81 for discussion.

### CODE REVIEW

**Comment by enuchi** [comment]
Thank you for this @RealSlimMahdi

**Comment by RealSlimMahdi** [comment]
No problem @enuchi, it's a pity I'd have like to be a contributor to your work 😜

**Comment by enuchi** [comment]
Sorry about that @RealSlimMahdi ! Tried to see if Github would add you as contributor but I think it only does that if you're the person who opens the PR. Your name is still in the commit history though 😄

**Comment by enuchi** [comment]
You could upgrade the version of react @RealSlimMahdi but you'd need to touch the lock file 😂

**Pull request merged**
