### PR TITLE
optimize webpack and other minor changes

### PR DESCRIPTION
**Pull request by enuchi**

### CODE REVIEW

**Comment by enuchi** [comment]
Updates webpack to among other things use cdn unpkg.com for client-side packages. See issue #19 .

**Comment by piavgh** [comment]
Hi @enuchi ,

Did you make this update to migrate the code to V8 engine (https://developers.google.com/apps-script/guides/v8-runtime) ?

Thanks.

**Comment by enuchi** [comment]
Yes, this PR changes the way external dependencies are used to fix the issue of large html files. It also updates some packages and uses the new v8 runtime. Are you having any issues with it?

**Comment by piavgh** [comment]
@enuchi : No, I don't have any issues with it yet.
I haven't worked with G Suite add-on for a while, now I have to work with it again and I see that Google released V8 for Apps Script.

Because I'm familiar with using this boilerplate so I just want to make sure I understand it correctly.

Thank you for your information. I will try this new code and report if there are any issues.

**Comment by piavgh** [comment]
@enuchi : I have an issue when adding new changes in my existing code.

When I added `new DynamicCdnWebpackPlugin()`, inside `clientConfigs` in `webpack.config.js`, the add-on doesn't show up on forms Add-on menu.

In browser console, I see `React is not defined`

When I removed this line, the add-on shows up again.

Is there any magic here? I mean ... did I forget something related to this webpack plugin?

**Comment by enuchi** [comment]
Hi @piavgh, I made a few other changes to the webpack file in this PR. I'd try using the whole new webpack config file, updating the entrypoints in the top of the file to match your needs, and make sure to install any new dependencies used, for instance DynamicCdnWebpackPlugin uses `dynamic-cdn-webpack-plugin` npm package. See the `package.json` file updates. Feel free to open a new issue with more details about what is happening if it is not working.

**Comment by piavgh** [comment]
@enuchi : Thank you very much. I found the problem.

In webpack.config.js, I used `const destination = path.resolve(__dirname, 'dist')` instead of `const destination = 'dist'` as you did

It worked with the previous webpack-clean configuration:

```javascript
const webpackCleanPlugin = new WebpackCleanPlugin(['main.js'], {
  basePath: path.join(__dirname, 'dist'),
})
```

**Pull request merged**
