### PR TITLE
bump to react17

### PR DESCRIPTION
**Pull request by RealSlimMahdi**
Hi @enuchi ,
This time I tried to do the PR properly with my poor software development skills (I am a data engineer :))
I bumped to the last React version.
I deployed the code and everything seems to work properly.
thanks,

### CODE REVIEW

**Comment by enuchi** [comment]
Just checking -- what version of npm are you using?

**Comment by RealSlimMahdi** [comment]
7.13.0, you are using v6 I guess?

**Comment by enuchi** [comment]
Yes -- that explains the large diff. It is upgrading to the new lock file version. I think it should be okay, just let me think if there are any downsides.

**Comment by RealSlimMahdi** [comment]
I have a second laptop, if you like I can downgrade to v6 and try from there.

**Comment by enuchi** [comment]
Yes, do you mind trying that? Let's leave the npm lockfile upgrade for a separate PR. You may just be able to do something like `npm install -g npm@6` and then when you're finished with the react installation run `npm install -g npm@7` but depends on your OS and setup.

**Comment by enuchi** [comment]
Closing after merging #92

**Pull request closed without merging**
